/**
 * Apply Cloudinary logo URLs to database using Prisma.
 * Reads the logo URLs from logo-urls.json and updates certifications.
 */

import { PrismaClient } from '@prisma/client';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const prisma = new PrismaClient();

// Issuer → logo key mapping
const ISSUER_TO_LOGO_KEY: Record<string, string> = {
  'Alibaba Cloud': 'alibaba-cloud',
  'Alibaba Cloud (Apsara Clouder)': 'alibaba-cloud',
  'Alibaba Cloud / ADSE': 'alibaba-cloud',
  'Google Cloud': 'google-cloud',
  'Codepolitan': 'codepolitan',
  'Dicoding Indonesia': 'dicoding',
  'IBM (Cognitive Class)': 'ibm',
  'Sanbercode': 'sanbercode',
  'RevoU': 'revou',
  'STMIK Jabar': 'stmik-jabar',
  'LPPM STMIK Jabar': 'stmik-jabar',
  'HIMATIF STMIK Jabar': 'stmik-jabar',
  'BEM STMIK Jabar': 'stmik-jabar',
  'HIMASI STMIK Jabar': 'stmik-jabar',
  'HIMASI': 'stmik-jabar',
  'JDA': 'jda',
  'Seminar Nasional': 'seminar',
  'Seminar Internasional': 'seminar',
  'Institut Teknologi Tangerang Selatan': 'itts',
  'Unknown': 'default',
};

async function main() {
  // Read logo URLs from the JSON file generated by upload script
  const logoUrlsPath = path.resolve(__dirname, '..', '..', 'scripts', 'logo-urls.json');
  const logoUrls: Record<string, string> = JSON.parse(fs.readFileSync(logoUrlsPath, 'utf-8'));

  console.log(`📋 Loaded ${Object.keys(logoUrls).length} logo URLs from Cloudinary\n`);

  // Get all certs
  const certs = await prisma.certification.findMany({ select: { id: true, issuer: true } });
  console.log(`📋 Total certifications: ${certs.length}\n`);

  let updated = 0;
  for (const cert of certs) {
    const key = ISSUER_TO_LOGO_KEY[cert.issuer];
    if (!key) {
      console.warn(`⚠️  No mapping: "${cert.issuer}" (${cert.id})`);
      continue;
    }
    const url = logoUrls[key];
    if (!url) {
      console.warn(`⚠️  No URL for key: ${key}`);
      continue;
    }

    await prisma.certification.update({
      where: { id: cert.id },
      data: { issuerLogo: url },
    });
    console.log(`✅ ${cert.id} → ${url.substring(0, 70)}...`);
    updated++;
  }

  console.log(`\n🎉 Updated ${updated}/${certs.length} certifications with Cloudinary logo URLs.`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
